#!/usr/bin/env bash

scenario_prepare() {
    base_prepare_snapshot_fixture
    write_text "${WORKSPACE_DIR}/reqpack.lua" "keep-me\n"
}

scenario_command() {
    printf 'cd %q && rqp --config %q snapshot --output reqpack.lua' "${WORKSPACE_DIR}" "${CONFIG_PATH}"
}

scenario_stdin() {
    printf 'n\n'
}

scenario_assert() {
    status="$(read_status)"
    if [ "${status}" = "0" ]; then
        printf 'expected existing snapshot output file prompt to abort\n' >&2
        exit 1
    fi
    assert_output_contains "already exists. Overwrite? [y/N]" "${STDOUT_PATH}"
    assert_output_contains "aborted." "${STDOUT_PATH}"
    assert_output_contains "keep-me" "${WORKSPACE_DIR}/reqpack.lua"
    assert_output_not_contains "-- Generated by ReqPack snapshot" "${WORKSPACE_DIR}/reqpack.lua"
}
