#include "cli_help_text.h"

#include "cli_parse_shared.h"

#include <string>

namespace {

const std::string PROGRAM_NAME = "rqp";
const std::string USAGE = "Usage: rqp <command> <system> [packages...] [additional systems/packages...] [flags...]";
const std::string HELP_DESCRIPTION = "Displays this help";
const std::string VERBOSE_DESCRIPTION = "Shows verbose command transcript and logger console output";

}  // namespace

namespace cli_internal {

std::string_view program_name() {
    return PROGRAM_NAME;
}

std::string_view usage_text() {
    return USAGE;
}

std::string_view help_description() {
    return HELP_DESCRIPTION;
}

std::string_view verbose_description() {
    return VERBOSE_DESCRIPTION;
}

HelpScanResult scan_help_arguments(const std::vector<std::string>& arguments) {
    HelpScanResult result;
    for (const std::string& argument : arguments) {
        if (is_help_flag_argument(argument)) {
            result.hasHelp = true;
        } else if (result.action == ActionType::UNKNOWN) {
            const ActionType candidate = parse_action_token(argument);
            if (candidate != ActionType::UNKNOWN) {
                result.action = candidate;
            }
        }
    }
    return result;
}

std::string general_help_text() {
    return PROGRAM_NAME + " - Unified Package Manager Interface\n"
           "\n" + USAGE + "\n"
           "\nOptions:\n"
           "  -h,--help               " + HELP_DESCRIPTION + "\n"
           "  -v,--verbose            " + VERBOSE_DESCRIPTION + "\n"
           "\nCommands:\n"
           "  install (i)             Installs requested packages\n"
           "  remove (rm)             Removes requested packages\n"
           "  update (up)             Updates requested packages\n"
           "  search                  Searches for packages\n"
           "  list                    Lists packages for a system\n"
           "  outdated                Shows outdated packages for a system\n"
           "  info                    Shows package info for a system\n"
           "  ensure [systems...]     Ensures plugin requirements are installed\n"
           "  sbom                    Exports planned graph as table or JSON\n"
           "  audit                   Audits planned graph for vulnerabilities\n"
           "  host                    Manages cached host system metadata\n"
           "  version                 Prints ReqPack version\n"
           "  test-plugin             Runs hermetic plugin conformance cases\n"
           "  snapshot                Snapshots installed packages to reqpack.lua\n"
           "  pack                    Builds .rqp or plugin-native package artifacts\n"
           "  serve                   Reads commands from stdin and keeps process running\n"
           "  remote                  Connects to remote profile from XDG config (~/.config/reqpack fallback)\n"
           "\nConfig:\n"
           "  --config <path>         Loads config from a custom Lua file\n"
           "  --config=<path>         Same as above\n"
           "  --registry <path>       Loads registry sources from a custom path\n"
           "  --registry=<path>       Same as above\n"
           "  --archive-password <value> Password for encrypted archives\n"
           "\nLogging:\n"
           "  --log-level <name>      Sets logger level (trace/debug/info/warn/error/critical)\n"
           "  --log-console           Forces logger console output on\n"
           "  --no-log-console        Disables logger console output\n"
           "  --log-pattern <value>   Sets spdlog text log pattern\n"
           "  --log-file <path>       Writes text logs to file\n"
           "  --structured-log-file <path> Writes structured JSONL logs to file\n"
           "  --log-capture-display   Mirrors display events into structured logs\n"
           "  --no-log-capture-display Stops mirroring display events into structured logs\n"
           "  --log-category <name>   Restricts structured logs to named category (repeatable)\n"
           "  --backtrace             Enables spdlog backtrace capture\n"
           "\nSBOM:\n"
           "  --format <name>         Uses table, json, or cyclonedx-json\n"
           "  --output <path>         Writes SBOM output to file\n"
           "\nAudit:\n"
           "  --format <name>         Uses table, json, cyclonedx-vex-json, or sarif\n"
           "  --output <path>         Writes audit output to file\n"
           "  --force                 Overwrites existing output file without prompting\n"
           "\nRun 'rqp <command> -h' for command-specific help.\n";
}

std::string command_help_text(ActionType action) {
    switch (action) {
        case ActionType::INSTALL:
            return
                "Usage: rqp install <system> [<package>...] [options]\n"
                "       rqp install <system> <local-path> [options]\n"
                "       rqp install <system1>:<package> <system2>:<package> [options]\n"
                "       rqp install <dir-path> [options]\n"
                "       rqp install --stdin [options]\n"
                "\n"
                "Install packages for one or more package managers.\n"
                "Alias: rqp i\n"
                "When a directory path is given (e.g. '.', './myproject', '/abs/path'),\n"
                "rqp reads a reqpack.lua manifest from that directory and installs\n"
                "all packages declared in it.\n"
                "When --stdin is given, rqp reads install payload lines or full install commands\n"
                "until EOF, then executes them as one combined install batch.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to use (e.g. apt, brew, npm)\n"
                "  <package>               One or more package names to install\n"
                "  <local-path>            Local path to install from (cannot mix with package names)\n"
                "  <system>:<package>      Scoped package for a specific system\n"
                "  <dir-path>              Directory containing a reqpack.lua manifest\n"
                "\n"
                "Manifest format (reqpack.lua):\n"
                "  return {\n"
                "    packages = {\n"
                "      { system = \"dnf\",  name = \"curl\" },\n"
                "      { system = \"npm\",  name = \"express\", version = \"4.18.0\" },\n"
                "    }\n"
                "  }\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --stdin                 Read install payload lines or commands from stdin until EOF\n"
                "  --dry-run               Show planned actions without executing them\n"
                "  --prompt-on-unsafe      Prompt before installing vulnerable packages\n"
                "  --abort-on-unsafe       Abort if vulnerable packages are found\n"
                "  --severity-threshold    Minimum severity to flag (low/medium/high/critical)\n"
                "  --score-threshold       Minimum CVSS score to flag (0.0-10.0)\n"
                "  --fail-on-unresolved-version    Abort if version cannot be resolved\n"
                "  --prompt-on-unresolved-version  Prompt if version cannot be resolved\n"
                "  --archive-password <value> Password for encrypted archives\n"
                "  --jobs <n>             Use exactly n workers for independent groups\n"
                "  --jobs-max             Use all logical CPU threads as workers\n"
                "  --stop-on-first-failure Stop after the first failing system\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp install apt curl git\n"
                "  rqp i apt curl git\n"
                "  rqp install npm express lodash brew jq\n"
                "  rqp install apt:curl npm:express\n"
                "  rqp install brew ./my-formula.rb\n"
                "  rqp install .\n"
                "  rqp install ./myproject\n"
                "  rqp install /absolute/path/to/project\n"
                "  printf 'install dnf curl\\ninstall npm express\\n' | rqp install --stdin\n";
        case ActionType::REMOVE:
            return
                "Usage: rqp remove <system> [<package>...] [options]\n"
                "       rqp remove <system1>:<package> <system2>:<package> [options]\n"
                "       rqp remove <dir-path> [options]\n"
                "       rqp remove --stdin [options]\n"
                "\n"
                "Remove packages from one or more package managers.\n"
                "Alias: rqp rm\n"
                "When a directory path is given (e.g. '.', './myproject', '/abs/path'),\n"
                "rqp reads a reqpack.lua manifest from that directory and removes\n"
                "all packages declared in it.\n"
                "When --stdin is given, rqp reads remove payload lines or full remove commands\n"
                "until EOF, then executes them as one combined remove batch.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to use (e.g. apt, brew, npm)\n"
                "  <package>               One or more package names to remove\n"
                "  <system>:<package>      Scoped package for a specific system\n"
                "  <dir-path>              Directory containing a reqpack.lua manifest\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --stdin                 Read remove commands from stdin until EOF\n"
                "  --dry-run               Show planned actions without executing them\n"
                "  --jobs <n>             Use exactly n workers for independent groups\n"
                "  --jobs-max             Use all logical CPU threads as workers\n"
                "  --stop-on-first-failure Stop after the first failing system\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp remove apt curl\n"
                "  rqp rm apt curl\n"
                "  rqp remove npm express brew jq\n"
                "  rqp remove apt:curl npm:lodash\n"
                "  rqp remove .\n"
                "  printf 'remove dnf curl\nremove npm express\n' | rqp remove --stdin\n";
        case ActionType::UPDATE:
            return
                "Usage: rqp update [options]\n"
                "       rqp update <system> [<package>...] [options]\n"
                "       rqp update <system1>:<package> <system2>:<package> [options]\n"
                "       rqp update <dir-path> [options]\n"
                "       rqp update <manifest-path>/reqpack.lua [options]\n"
                "       rqp update --stdin [options]\n"
                "\n"
                "Update ReqPack itself, plugin wrappers, or packages for one or more package managers.\n"
                "Alias: rqp up\n"
                "Without a system argument, ReqPack downloads matching release binary from its configured release source.\n"
                "With a system argument and no package list, ReqPack refreshes that plugin wrapper to its newest tagged version when the source is Git-backed.\n"
                "Use '--all' with a system to update all packages for that system instead.\n"
                "Directory and direct reqpack.lua manifest input update all declared packages.\n"
                "When --stdin is given, rqp reads update payload lines or full update commands\n"
                "until EOF, then executes them as one combined update batch.\n"
                "Use 'rqp update --all' to refresh all known plugin wrappers.\n"
                "To update a package-manager binary itself through ReqPack's wrapper layer, use 'rqp update sys <tool>'.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to use (e.g. apt, brew, npm)\n"
                "  <package>               One or more package names to update (optional)\n"
                "  <system>:<package>      Scoped package for a specific system\n"
                "  <dir-path>              Directory containing a reqpack.lua manifest\n"
                "  <manifest-path>         Explicit reqpack.lua manifest file\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --stdin                 Read update payload lines or commands from stdin until EOF\n"
                "  --dry-run               Show planned actions without executing them\n"
                "  --all                   Update all packages for system, or all plugin wrappers without a system\n"
                "  --prompt-on-unsafe      Prompt before applying vulnerable updates\n"
                "  --abort-on-unsafe       Abort if vulnerable packages are found\n"
                "  --severity-threshold    Minimum severity to flag (low/medium/high/critical)\n"
                "  --score-threshold       Minimum CVSS score to flag (0.0-10.0)\n"
                "  --jobs <n>             Use exactly n workers for independent groups\n"
                "  --jobs-max             Use all logical CPU threads as workers\n"
                "  --stop-on-first-failure Stop after the first failing system\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp update\n"
                "  rqp up\n"
                "  rqp update --all\n"
                "  rqp up --all\n"
                "  rqp update pip\n"
                "  rqp update pip --all\n"
                "  rqp update apt --dry-run\n"
                "  rqp update npm express brew\n"
                "  rqp update sys pip\n"
                "  rqp update apt:curl npm:express\n"
                "  rqp update .\n"
                "  rqp update ./reqpack.lua\n"
                "  printf 'update dnf curl\\nquill:zeno\\n' | rqp update --stdin\n";
        case ActionType::SEARCH:
            return
                "Usage: rqp search <system> <query> [options]\n"
                "\n"
                "Search for packages in a package manager.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to search in (e.g. apt, brew, npm)\n"
                "  <query>                 Search term or package name\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --arch <value>          Filter search results by architecture (repeatable)\n"
                "  --type <value>          Filter search results by package type/class (repeatable)\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  rqp search apt curl\n"
                "  rqp search npm react\n"
                "  rqp search brew \"json tool\"\n"
                "  rqp search dnf python3 --arch noarch --arch x86_64\n"
                "  rqp search dnf python3 --type doc --type devel\n";
        case ActionType::LIST:
            return
                "Usage: rqp list [<system>|<dir-path>] [options]\n"
                "\n"
                "List installed packages for a package manager.\n"
                "If no system is specified, all known primary systems are queried.\n"
                "Directory input loads reqpack.lua and lists matching installed packages.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to list packages for (optional)\n"
                "  <dir-path>              Directory containing a reqpack.lua manifest\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --arch <value>          Filter listed packages by architecture (repeatable)\n"
                "  --type <value>          Filter listed packages by package type/class (repeatable)\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  rqp list\n"
                "  rqp list apt\n"
                "  rqp list npm\n"
                "  rqp list brew\n"
                "  rqp list .\n"
                "  rqp list ./project\n"
                "  rqp list dnf --arch x86_64\n"
                "  rqp list dnf --type doc --type devel\n";
        case ActionType::INFO:
            return
                "Usage: rqp info [<system> [<package>]] [options]\n"
                "\n"
                "Show detailed information about ReqPack, plugin wrapper, or package.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager or plugin wrapper to query (optional)\n"
                "  <package>               Package name to get info for (optional)\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  rqp info\n"
                "  rqp info apt\n"
                "  rqp info apt curl\n"
                "  rqp info npm express\n"
                "  rqp info brew jq\n";
        case ActionType::ENSURE:
            return
                "Usage: rqp ensure [<system>...] [options]\n"
                "\n"
                "Ensure plugin requirements are installed for one or more systems.\n"
                "If no systems are specified, all known systems are checked.\n"
                "\n"
                "Arguments:\n"
                "  <system>                One or more package managers to check (optional)\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --dry-run               Show planned actions without executing them\n"
                "  --stop-on-first-failure Stop after the first failing system\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp ensure\n"
                "  rqp ensure apt brew\n";
        case ActionType::SBOM:
            return
                "Usage: rqp sbom [<system>...] [options]\n"
                "\n"
                "Export a Software Bill of Materials (SBOM) for installed packages.\n"
                "If no systems are specified, all known systems are included.\n"
                "\n"
                "Arguments:\n"
                "  <system>                One or more package managers to include (optional)\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --format <name>         Output format: table, json, cyclonedx-json (default: table)\n"
                "  --output <path>         Write SBOM output to file instead of stdout\n"
                "  --wide                  Use wider table layout for terminal output\n"
                "  --no-wrap               Do not wrap table columns; let terminal handle overflow\n"
                "  --force                 Overwrite existing output file without prompting\n"
                "  --sbom-skip-missing-packages Skip requested packages that cannot be resolved\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp sbom\n"
                "  rqp sbom apt npm\n"
                "  rqp sbom --format json\n"
                "  rqp sbom --format cyclonedx-json --output sbom.json\n";
        case ActionType::AUDIT:
            return
                "Usage: rqp audit [<system>...] [options]\n"
                "       rqp audit <system1>:<package> <system2>:<package> [options]\n"
                "       rqp audit <dir-path> [options]\n"
                "       rqp audit <manifest-path>/reqpack.lua [options]\n"
                "\n"
                "Audit planned packages for vulnerabilities and export findings.\n"
                "If no system is specified, all known primary systems are included.\n"
                "If a system is given without explicit packages, rqp audits installed packages reported by that system.\n"
                "Directory and direct reqpack.lua manifest input are supported.\n"
                "Without --output, audit prints a table and returns exit code 1 when findings exist.\n"
                "With --output, findings are exported but do not change the exit code.\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --format <name>         Output format: table, json, cyclonedx-vex-json, sarif\n"
                "  --output <path>         Write audit output to file instead of stdout\n"
                "  --wide                  Use wider table layout for terminal output\n"
                "  --no-wrap               Do not wrap table columns; let terminal handle overflow\n"
                "  --force                 Overwrite existing output file without prompting\n"
                "  --non-interactive       Disable all prompts (use defaults)\n"
                "\n"
                "Examples:\n"
                "  rqp audit\n"
                "  rqp audit npm react\n"
                "  rqp audit npm:react maven:org.junit:junit\n"
                "  rqp audit .\n"
                "  rqp audit ./reqpack.lua\n"
                "  rqp audit --format cyclonedx-vex-json --output audit.json\n"
                "  rqp audit --format sarif --output audit.sarif\n";
        case ActionType::OUTDATED:
            return
                "Usage: rqp outdated [<system>|<dir-path>] [options]\n"
                "\n"
                "Show packages that have newer versions available.\n"
                "If no system is specified, all known primary systems are queried.\n"
                "Directory input loads reqpack.lua and shows matching outdated installed packages.\n"
                "\n"
                "Arguments:\n"
                "  <system>                Package manager to check (optional)\n"
                "  <dir-path>              Directory containing a reqpack.lua manifest\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --arch <value>          Filter outdated packages by architecture (repeatable)\n"
                "  --type <value>          Filter outdated packages by package type/class (repeatable)\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  rqp outdated\n"
                "  rqp outdated dnf\n"
                "  rqp outdated maven\n"
                "  rqp outdated .\n"
                "  rqp outdated ./project\n"
                "  rqp outdated dnf --arch noarch\n"
                "  rqp outdated dnf --type doc\n";
        case ActionType::HOST:
            return
                "Usage: rqp host refresh\n"
                "\n"
                "Refresh the cached host system snapshot used by plugins via context.host and reqpack.host.\n"
                "This forces a live probe and rewrites the cache file under XDG cache.\n"
                "\n"
                "Subcommands:\n"
                "  refresh                 Force a live refresh of host metadata cache\n"
                "\n"
                "Examples:\n"
                "  rqp host refresh\n";
        case ActionType::SNAPSHOT:
            return
                "Usage: rqp snapshot [options]\n"
                "\n"
                "Snapshot all currently installed packages (tracked by ReqPack history)\n"
                "into a reqpack.lua manifest. Use 'rqp install .' to restore on\n"
                "another machine.\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --output <path>         Write manifest to file instead of stdout\n"
                "  --force                 Overwrite existing file without prompting\n"
                "\n"
                "Examples:\n"
                "  rqp snapshot\n"
                "  rqp snapshot --output reqpack.lua\n"
                "  rqp snapshot --output reqpack.lua --force\n";
        case ActionType::PACK:
            return
                "Usage: rqp pack [project-dir] [options]\n"
                "       rqp pack <system> <project-dir> [options]\n"
                "\n"
                "Build package artifacts from project directories.\n"
                "Without <project-dir>, ReqPack packs current directory.\n"
                "With one positional path, ReqPack builds a builtin .rqp package.\n"
                "With <system> plus path, ReqPack dispatches to plugin-native pack support if available.\n"
                "\n"
                "Arguments:\n"
                "  <project-dir>           Project directory to pack (default: .)\n"
                "  <system>                Optional package manager with native pack support\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --output <path>         Write artifact to explicit output path\n"
                "  --payload-dir <path>    External payload tree for builtin .rqp mode\n"
                "  --force                 Overwrite existing output file without prompting\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  rqp pack\n"
                "  rqp pack ./my-package\n"
                "  rqp pack ./my-package --output ./dist/demo.rqp\n"
                "  rqp pack ./my-package --payload-dir ./rootfs\n"
                "  rqp pack deb ./debian-project --output ./dist/demo.deb\n";
        case ActionType::SERVE:
            return
                "Usage: rqp serve --stdin [options]\n"
                "       rqp serve --remote [--json|--http|--https] [options]\n"
                "\n"
                "Serve ReqPack commands either from stdin or over a remote socket.\n"
                "stdin mode executes one command per line until EOF.\n"
                "remote mode starts a TCP server and returns command responses to clients.\n"
                "Without protocol flag, remote mode accepts text protocol and auto-detects JSON requests per connection.\n"
                "Server-side users can be loaded from $XDG_CONFIG_HOME/reqpack/remote.lua (or ~/.config/reqpack/remote.lua) under users = { ... }.\n"
                "Admin users may run: shutdown, connections count, connections list, reload-config.\n"
                "--token/--username/--password remain fallback auth when no valid server users exist.\n"
                "\n"
                "Options:\n"
                "  -h,--help               Displays this help\n"
                "  --stdin                 Read commands from stdin\n"
                "  --remote                Start remote TCP command server\n"
                "  --json                  Force JSON Lines protocol for all remote clients\n"
                "  --http                  Reserved for future HTTP server mode\n"
                "  --https                 Reserved for future HTTPS server mode\n"
                "  --bind <addr>           Bind remote server to address (default: 127.0.0.1)\n"
                "  --port <n>              Bind remote server to port (default: 4545)\n"
                "  --token <value>         Require token authentication for remote clients\n"
                "  --username <name>       Require username/password authentication\n"
                "  --password <value>      Password for username/password authentication\n"
                "  --readonly              Allow read-only commands only\n"
                "  --max-connections <n>   Maximum concurrent remote clients\n"
                "  --non-interactive       Disable all prompts\n"
                "\n"
                "Examples:\n"
                "  printf 'install dnf curl\\nlist dnf\\n' | rqp serve --stdin\n"
                "  rqp serve --remote --bind 127.0.0.1 --port 4545 --token secret\n"
                "  rqp serve --remote --json --readonly --max-connections 4\n";
        case ActionType::REMOTE:
            return
                "Usage: rqp remote <profile> [<command>...]\n"
                "\n"
                "Connect to remote profile from $XDG_CONFIG_HOME/reqpack/remote.lua or ~/.config/reqpack/remote.lua.\n"
                "With forwarded command, execute once and exit. Without command, start interactive text session.\n"
                "Forwarded install of local file uploads it to text/auto remotes: rqp remote <profile> install <system> <local-file>.\n"
                "JSON remotes reject file uploads.\n"
                "\n"
                "Arguments:\n"
                "  <profile>               Profile name defined in $XDG_CONFIG_HOME/reqpack/remote.lua\n"
                "  <command>               Optional forwarded rqp command\n"
                "\n"
                "Profile fields:\n"
                "  host/url                Remote host or IPv4 address\n"
                "  port                    Remote TCP port\n"
                "  protocol                auto, text, json, http, or https\n"
                "  token                   Token auth for text/json remotes\n"
                "  username/password       Basic auth for text/json remotes\n"
                "\n"
                "Examples:\n"
                "  rqp remote dev list apply\n"
                "  rqp remote prod\n";
        default:
            return {};
    }
}

}  // namespace cli_internal
