#!/usr/bin/env bash

scenario_prepare() {
    base_prepare_snapshot_fixture
}

scenario_command() {
    printf 'cd %q && rqp --config %q snapshot' "${WORKSPACE_DIR}" "${CONFIG_PATH}"
}

scenario_assert() {
    assert_equals "0" "$(read_status)" "snapshot stdout exits zero"
    assert_output_contains "-- Generated by ReqPack snapshot" "${STDOUT_PATH}"
    assert_output_contains '{ system = "moss", name = "luma", version = "1.0.0" }' "${STDOUT_PATH}"
    assert_output_contains '{ system = "quill", name = "zeno", version = "1.0.0" }' "${STDOUT_PATH}"
}
