#include "core/snapshot_exporter.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>

namespace {

// Lua string escaping: backslash and double-quote only (values from history
// should be safe, but be defensive).
std::string lua_escape(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (const char c : s) {
        if (c == '\\') { out += "\\\\"; }
        else if (c == '"') { out += "\\\""; }
        else { out += c; }
    }
    return out;
}

} // namespace

SnapshotExporter::SnapshotExporter(const ReqPackConfig& cfg) : config(cfg) {}

std::string SnapshotExporter::resolveOutputPath(const Request& request) const {
    if (!request.outputPath.empty()) {
        return request.outputPath;
    }
    return {};
}

std::string SnapshotExporter::render(const std::vector<InstalledEntry>& entries) const {
    std::ostringstream out;
    out << "-- Generated by ReqPack snapshot\n";
    out << "return {\n";
    out << "  packages = {\n";
    for (const InstalledEntry& e : entries) {
        out << "    { system = \"" << lua_escape(e.system)
            << "\", name = \"" << lua_escape(e.name)
            << "\", version = \"" << lua_escape(e.version)
            << "\" },\n";
    }
    out << "  },\n";
    out << "}\n";
    return out.str();
}

bool SnapshotExporter::exportSnapshot(const Request& request) const {
    HistoryManager history(this->config);
    const std::vector<InstalledEntry> entries = history.loadInstalledState();

    if (entries.empty()) {
        std::cerr << "snapshot: no installed packages tracked in history.\n"
                     "Ensure history.trackInstalled is enabled in your config.\n";
        // Still write an empty manifest — not a hard error.
    }

    // Sort by system then name for deterministic output.
    std::vector<InstalledEntry> sorted = entries;
    std::sort(sorted.begin(), sorted.end(), [](const InstalledEntry& a, const InstalledEntry& b) {
        if (a.system != b.system) { return a.system < b.system; }
        return a.name < b.name;
    });

    const std::string rendered = render(sorted);
    const std::string outputPath = resolveOutputPath(request);

    if (outputPath.empty()) {
        std::cout << rendered;
        std::cout.flush();
        return true;
    }

    std::filesystem::path filePath(outputPath);
    if (filePath.is_relative()) {
        filePath = std::filesystem::current_path() / filePath;
    }
    const std::string resolvedPath = filePath.string();

    if (std::filesystem::exists(filePath)) {
        const bool force = std::find(request.flags.begin(), request.flags.end(), "force") != request.flags.end();
        if (!force) {
            std::cerr << resolvedPath << " already exists. Overwrite? [y/N] " << std::flush;
            std::string answer;
            if (!std::getline(std::cin, answer) || (answer != "y" && answer != "Y")) {
                std::cerr << "aborted.\n";
                return false;
            }
        }
    }

    std::error_code ec;
    const std::filesystem::path parentPath = filePath.parent_path();
    if (!parentPath.empty()) {
        std::filesystem::create_directories(parentPath, ec);
        if (ec) {
            std::cerr << "snapshot: failed to create output directory: " << resolvedPath << '\n';
            return false;
        }
    }

    std::ofstream output(resolvedPath, std::ios::binary | std::ios::trunc);
    if (!output.is_open()) {
        std::cerr << "snapshot: failed to open output path: " << resolvedPath << '\n';
        return false;
    }

    output << rendered;
    if (!output.good()) {
        std::cerr << "snapshot: failed to write output path: " << resolvedPath << '\n';
        return false;
    }

    std::cout << resolvedPath << '\n';
    std::cout.flush();
    return true;
}
