#!/usr/bin/env bash

scenario_prepare() {
    base_prepare_snapshot_fixture
    write_text "${WORKSPACE_DIR}/reqpack.lua" "keep-me\n"
}

scenario_command() {
    printf 'cd %q && rqp --config %q snapshot --output reqpack.lua --force' "${WORKSPACE_DIR}" "${CONFIG_PATH}"
}

scenario_assert() {
    assert_equals "0" "$(read_status)" "snapshot output force overwrite exits zero"
    assert_output_contains "${WORKSPACE_DIR}/reqpack.lua" "${STDOUT_PATH}"
    assert_output_not_contains "Overwrite? [y/N]" "${STDOUT_PATH}"
    assert_file_exists "${WORKSPACE_DIR}/reqpack.lua"
    assert_output_contains "-- Generated by ReqPack snapshot" "${WORKSPACE_DIR}/reqpack.lua"
    assert_output_contains '{ system = "moss", name = "luma", version = "1.0.0" }' "${WORKSPACE_DIR}/reqpack.lua"
    assert_output_contains '{ system = "quill", name = "zeno", version = "1.0.0" }' "${WORKSPACE_DIR}/reqpack.lua"
    assert_output_not_contains "keep-me" "${WORKSPACE_DIR}/reqpack.lua"
}
